version: "3.9"
services:
    mongo:
        image: mongo
        restart: always
        volumes:
            - mongo_data:/data/db
        ports:
            - 27017-27019:27017-27019

    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8082:8081

volumes:
    mongo_data: {}
